### ISSUE TITLE
Mention the option to lint added files in addition to modified files

### ISSUE THREAD

**Issue by jouni** [vale-cli/vale-action#22]
First, thank you for the great tool!

The readme describes how to lint modified files in a PR, using the [file-changes action](https://github.com/marketplace/actions/file-changes-action) and `files: ${{ steps.file_changes.outputs.files_modified }}`. That omits _files added in a PR_, as far as I understand.

At least for us, this causes the lint process to stall, and eventually timeout (after 5 hours), for some reason, if a PR only adds files and doesn’t modify any existing ones.

Something like is probably a good idea to add to the readme:

```
files: '${{ steps.file_changes.outputs.files_modified }} ${{ steps.file_changes.outputs.files_added }}'
```

Update: well, the above doesn’t actually work, the path it produces is not valid. Not sure how to combine the two arrays together. Using `steps.file_changes.outputs.files` doesn’t feel correct either, as it contains removed files.

**Comment by jdkato** [comment]
Should have been addressed by #23.

**Comment by jouni** [comment]
Oh, wow, annotating only the changed lines sounds like the best solution! Thanks, we’ll try that by using `@master`.

**Comment by jouni** [comment]
Hmm. I tried to update the [workflow config](https://github.com/vaadin/docs/blob/master/.github/workflows/vale-integration-workflow.yml) correctly, but now I get [an error](https://github.com/vaadin/docs/pull/40/checks?check_run_id=1394822428) from it:

```yaml
name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@master
      with:
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/Google/releases/latest/download/Google.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        files: __onlyModified
        onlyAnnotateModifiedLines: true

      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

![Screenshot 2020-11-13 at 10 43 07](https://user-images.githubusercontent.com/66382/99047613-1b1e5d00-259d-11eb-8aed-984ae1b56837.png)
