### ISSUE TITLE
Fail job if there are any suggestions/warnings/errors

### ISSUE THREAD

**Issue by paddyroddy** [vale-cli/vale-action#26]
I'm a perfectionist so would like the action to be very strict such that I can change if I push a mistake. Is it possible to do this without changing the `level: error` in all the config files?

**Comment by paddyroddy** [comment]
actually I've just tried changing `level: error` in my yaml files and that doesn't work. The job passes which means I don't get an email that it failed - which is essentially what I'm after

![image](https://user-images.githubusercontent.com/15052188/98918590-b5ab6d00-24c5-11eb-8bcb-a76b6f530504.png)

**Comment by ArtFlag** [comment]
Same thing here. 
The workflow doesn't fail even though my vale job is failing. (see number of errors below).

<img width="354" alt="Screenshot 2020-12-10 at 18 30 32" src="https://user-images.githubusercontent.com/25686502/101808550-c37cfe00-3b16-11eb-937d-ebcc172cc0b9.png">

Any idea?

**Comment by svx** [comment]
Same thing here. 
Locally everything works and the check is failing, running it as workflow, it is reporting errors but not failing.

Here is the workflow
```yml
name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@master
      with:
        # Optional
        files: docs
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

I also tried with `errata-ai/vale-action@v1.3.0` and it makes no difference :)

**Comment by jdkato** [comment]
The action currently creates two jobs: the first should always pass (it sets up and runs Vale) and the second should fail if there are errors (it creates the annotations). 

This appears to be what is shown in the screenshot above: `vale_run` passed and `Vale` failed.

**Comment by paddyroddy** [comment]
Yes but I would like the whole job to fail in this instance i.e. I should get an email which I don't

**Comment by jdkato** [comment]
This is now possible by using the new reviewdog-based action with `fail_on_error: true`:

```yaml
name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Comment by paddyroddy** [comment]
I've just tested this, and I don't believe it's working.

In my repo I run on all `.tex` files, as prior to https://github.com/errata-ai/vale-action/issues/37 there was no way to ignore certain files. Running `vale .` on the command line, errors are found in 5 files.
<img width="597" alt="image" src="https://user-images.githubusercontent.com/15052188/167869264-ec42ffbe-b97a-4c6e-b9d3-c3325f5a7324.png">

Prior to changing my CI, my last CI run was like the following:
![image](https://user-images.githubusercontent.com/15052188/167869686-11b075d6-be6b-4834-adf9-7358b04d68bf.png)

Now with changing `@v1.5.0` to `@reviewdog` and adding `fail_on_error: true`, the only real change is that I don't get the second `Vale` step. Also, crucially, the job doesn't fail as expected. I have not implemented https://github.com/errata-ai/vale-action/issues/37.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/15052188/167870013-56f6f6b9-e62d-4411-a393-fb3d8a45b845.png">

**Comment by jdkato** [comment]
Did you make a change related to #37? 

It looks like the second screenshot didn't find any errors,    rather than finding them and not failing.

**Comment by paddyroddy** [comment]
Nope, as stated in my reply at this point I have not implemented #37 - was going to look into this now.

**Comment by jdkato** [comment]
Could you share the full configuration, including your `.vale.ini`?

**Comment by paddyroddy** [comment]
Sure. The relevant bit of the GitHub action
```
vale:
    runs-on: ubuntu-latest
    steps:
        - name: checkout source
          uses: actions/checkout@v3

        - name: Run Vale
          uses: errata-ai/vale-action@reviewdog
          env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          with:
              fail_on_error: true
```

And my `.vale.ini`
```
StylesPath = .github/styles
MinAlertLevel = suggestion

[*.tex]
BasedOnStyles=18F,\
              custom,\
              Google,\
              Microsoft,\
              Openly,\
              PlainLanguage,\
              proselint,\
              The-Economist,\
              Vale,\
              write-good

# Disable
Vale.Spelling = NO
```
