### ISSUE TITLE
_onlyModified is failing

### ISSUE THREAD

**Issue by tjperry07** [vale-cli/vale-action#27]
I'm testing out the [Vale action ](https://github.com/errata-ai/vale-action#files-default-all)for onlyModified and I am getting the following failure. 

`Warning: User-specified path (__onlyModified) is invalid; falling back to 'all'.`

You can review my code and test here https://github.com/tjperry07/vale-setup/pull/1/checks?check_run_id=1413681722

```
Run errata-ai/vale-action@v1.3.0
/usr/bin/docker run --name ad72896c53a74836b0358e95b19b1553_016fa3 --label 179394 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_FILES -e INPUT_STYLES -e INPUT_CONFIG -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/vale-setup/vale-setup":"/github/workspace" 179394:ad72896c53a74836b0358e95b19b1553  "" "" "__onlyModified" "false"
Warning: User-specified path (__onlyModified) is invalid; falling back to 'all'.
Vale: Found 0 suggestion(s), 0 warning(s), and 4 error(s).
```

action file
```
name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        # Optional
        # styles: |
        #   https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
        #   https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

        # # Optional
        # config: https://raw.githubusercontent.com/errata-ai/vale/master/.vale.ini

        # Optional
        files: __onlyModified
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Comment by tjperry07** [comment]
It also returns an error for `onlyAnnotateModifiedLines`
`Warning: Unexpected input(s) 'onlyAnnotateModifiedLines', valid inputs are ['entryPoint', 'args', 'styles', 'config', 'files', 'debug']`

**Comment by jdkato** [comment]
These are unreleased features still, so you need to use the `@master` version (not `@v1.3.0`) to get access to them.

**Comment by jouni** [comment]
I tried using `@master` but got a slightly different error:

```
Error: Command failed with exit code 128: git diff --name-only undefined
```

I mentioned it here: https://github.com/errata-ai/vale-action/issues/22#issuecomment-726618738

**Comment by tjperry07** [comment]
I got the same error as @jouni when using `@master`. 

This works to check only modified files. It uses another action to grab only changed files and then vale checks that file. This works until _onlyModified is working.

```
name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Get Changed Files
      id: get_changed_files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        files: '${{ steps.get_changed_files.outputs.all }}'
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

**Comment by tcmetzger** [comment]
Just raising my hand to support adding onlyAnnotateModifiedLines to this great action. And thanks to @tjperry07 for the workaround!

**Comment by robb-romans** [comment]
Hi, looking forward to using this flag. Any news on a fix? Thanks.

**Comment by jdkato** [comment]
Getting a new release out is on my to-do list, but I don't have a concrete timeline.

**Comment by jdkato** [comment]
@pierrebeitz do you have any thoughts here?

My inclination is to move away from using raw Git commands in favor of using GitHub's API ([`/compare/`](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#compare-two-commits) and  [`pull-requests-files`](https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-pull-requests-files)). I think this will also allow us to avoid having to call `ensureGitHistory`.

**Comment by pierrebeitz** [comment]
@jdkato at first sight that sounds very reasonable! 
I plan to have a deeper look at this after Jan 4 (in case the issue persists till then).

**Comment by jdkato** [comment]
This should be fixed on `@master` now. Pending more testing, I'll make a new release.

**Comment by jouni** [comment]
To report back: I just updated our workflow, and it seems to be working nicely. Notably, I changed from [push] to [pull_request], and now the workflow checks all files within a PR, not just the ones within one commit.

Here’s our config:

```yaml
name: Vale
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: vale
        uses: errata-ai/vale-action@master
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          config: https://raw.githubusercontent.com/vaadin/docs/master/.vale.ini
          files: __onlyModified
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
