### ISSUE TITLE
Error: Cannot find module '@actions/http-client'

### ISSUE THREAD

**Issue by panovst** [vale-cli/vale-action#33]
Hello!
please tell me how to fix this error?

![Selection_018](https://user-images.githubusercontent.com/823344/112439963-cb298100-8d5a-11eb-8796-2d37eb312d49.png)

Vale config
```
name: Vale linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Vale
        uses: errata-ai/vale-action@v1.3.0
        with:
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

```
