### ISSUE TITLE
Unable to run action - E100 [.vale.ini] Runtime error  open : no such file or directory

### ISSUE THREAD

**Issue by Matthew-dB** [vale-cli/vale-action#40]
Hiya,

I'm currently unable to get the action for Vale running. On my own machine I can run Vale fine with the below files using `vale --config=".github/.vale.ini" --ext=".md" /local/path/to/repo`

Things I've tried:
* Running the pipeline with the Microsoft and write-good styles not committed to git
* Changing the stylepath to `.github/styles` (this then breaks execution on my local machine, as it tries to find `.github/.github/styles`)

Any pointers as to where I'm going wrong would be much appreciated.

<details>
  <summary>Action file</summary>
  
  ```yaml
  name: Linting
  on:
    pull_request:
      branches:
        - main
  
  jobs:
    prose:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@master
  
      - name: Vale
        uses: errata-ai/vale-action@v1.4.0
        with:
          # Optional
          styles: |
            https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          # Optional
          files: __onlyModified
          debug: true
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ```
</details>

<details>
  <summary>.vale.ini file:</summary>
  
  ```
  StylesPath = .github/styles
  MinAlertLevel = warning
  
  Vocab = Documentation
  
  [*.md]
  BasedOnStyles = Vale, Microsoft, write-good
  write-good.Passive = NO
  write-good.E-Prime = NO
  Microsoft.We = suggestion
  Microsoft.Terms = suggestion
  ```
</details>

<details>
  <summary>Full output of Vale step</summary>
  
  ```
  Run errata-ai/vale-action@v1.4.0
    with:
      styles: https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
    https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
    
      files: __onlyModified
      debug: true
      onlyAnnotateModifiedLines: false
    env:
      GITHUB_TOKEN: ***
  /usr/bin/docker run --name a33c1460ee904495e49d38f57d5c57d5e75f3_e9d2a1 --label 8a33c1 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_STYLES -e INPUT_FILES -e INPUT_DEBUG -e INPUT_CONFIG -e INPUT_ONLYANNOTATEMODIFIEDLINES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/es-foundational-docs/es-foundational-docs":"/github/workspace" 8a33c1:460ee904495e49d38f57d5c57d5e75f3  "https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
  https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
  " "" "__onlyModified" "false" "true"
  Using Vale v2.8.2
  Installing style 'Microsoft' ...
  /bin/vale install Microsoft https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
  E100 [.vale.ini] Runtime error
  
  open : no such file or directory
  
  Execution stopped with code 1.
  Error: The process '/bin/vale' failed with exit code 2
  ```
</details>

<details>
  <summary>Folder structure</summary>
  
  📦es-foundational-docs
   ┣ 📂.github
   ┃ ┣ 📂styles
   ┃ ┃ ┣ 📂Microsoft
   ┃ ┃ ┃ ┣ 📜AMPM.yml
   ┃ ┃ ┃ ┣ 📜 ... Various other files ...
   ┃ ┃ ┃ ┗ 📜meta.json
   ┃ ┃ ┣ 📂Vocab
   ┃ ┃ ┃ ┗ 📂Documentation
   ┃ ┃ ┃ ┃ ┣ 📜accept.txt
   ┃ ┃ ┃ ┃ ┗ 📜reject.txt
   ┃ ┃ ┗ 📂write-good
   ┃ ┃ ┃ ┣ 📜Cliches.yml
   ┃ ┃ ┃ ┣ 📜 ... Various other files ...
   ┃ ┃ ┃ ┗ 📜meta.json
   ┃ ┣ 📂workflows
   ┃ ┃ ┗ 📜main.yaml
   ┃ ┗ 📜.vale.ini
   ┣ 📂Postmortems
   ┃ ┣ 📂3553877
   ┃ ┃ ┗ 📜Postmortem.md
   ┃ ┣ 📂TEMPLATE
   ┃ ┃ ┣ 📜README.md
   ┃ ┃ ┗ 📜postmortem-template.md
   ┃ ┗ 📜README.md
   ┗ 📜README.md
</details>
