### ISSUE TITLE
Linter unable to create annotations; printing Vale alerts instead.

### ISSUE THREAD

**Issue by ramyaparimi** [vale-cli/vale-action#52]
This is my workflow:

```
name: Linter as style guide

on:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Vale
        uses: errata-ai/vale-action@cb5ab4acdaf3169b1b5e5b4785d844aaea6366a0
        with:
          onlyAnnotateModifiedLines: true
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

My .vale.ini

```StylesPath = styles

# suggestion, warning or error
MinAlertLevel = warning 

Vocab = Docs

[*.md]
BasedOnStyles = Vale,Vocab

TokenIgnores = (\`{1}((.|\n)*?)\`{1}), \
               \[([^\[]+)\](\(.*\)), \
               {%.*?%}, \ 
               {{.*?}}, \  
               (.|\/|-)?github(\/|-)?, \
               (\`{3}((.|\n)*?)\`{3})
StylesPath = styles

# suggestion, warning or error
MinAlertLevel = warning 

Vocab = Docs

[*.md]
BasedOnStyles = Vale,Vocab

TokenIgnores = (\`{1}((.|\n)*?)\`{1}), \
               \[([^\[]+)\](\(.*\)), \
               {%.*?%}, \ 
               {{.*?}}, \  
               (.|\/|-)?github(\/|-)?, \
               (\`{3}((.|\n)*?)\`{3})
```

This posting annotations correctly until last week. I noticed this happening only this week. 

<img width="965" alt="image" src="https://user-images.githubusercontent.com/33761166/149544237-e0d37c3b-0cf9-43f9-89a3-9470575fda44.png">
