### ISSUE TITLE
Vale update

### ISSUE THREAD

**Issue by Stanzilla** [vale-cli/vale-action#53]
Hey there, could there maybe be a way to specify which version of Vale to use? Currently the action uses 2.10.3 while the latest is 2.15.0, which has quite a few changes and means I have different results in my CI vs locally.

**Comment by tjperry07** [comment]
yes. Use the @ to specify the version in the action.
But the action and the CI are on different releases. 
```
    - name: Vale
      uses: errata-ai/vale-action@v1.4.2
      with:
        onlyAnnotateModifiedLines: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
