### ISSUE TITLE
workaround for PR from forked repo fail with onlyAnnotateModifiedLines option

### ISSUE THREAD

**Issue by alexfauquette** [vale-cli/vale-action#58]
Hi, I encounter a problem with using the workaround for PR from a forked repo.

When setting `onlyAnnotateModifiedLines: true` I get no error added to the PR and the action display a warning `'Unrecognized event: workflow_run'` and no comment is added to the modified lines.

- If I remove this option I obtain comments on unmodified lines
- If I run the action with `pull_request` event instead of `workflow_run` it works fine

I found that the error message comes from [getCommits](https://github.com/errata-ai/vale-action/blob/8683aa9e6370d27cefcbed7766979dcd021293ad/src/git.ts#L64) message which seems to support only support `pull_request` and `push` events.

--- 
If it can help, this are the workflow files
```yml
name: Linting

on:
  workflow_run:
    workflows: [PR check]
    types:
      - completed
  workflow_dispatch:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # get the SHA from workflow triggered by pull_request
      - name: Open sha file
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: pull-request-sha
      - name: Grab pull request sha1
        run: |
          pr_sha=`cat pr-sha.txt`
          echo "PR_SHA=$pr_sha" >> $GITHUB_ENV

      - name: Vale
        uses: errata-ai/vale-action@master
        with:
          styles: |
            https://github.com/errata-ai/Google/releases/latest/download/Google.zip
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
            
          onlyAnnotateModifiedLines: true

          files: docs/data
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OVERRIDE_GITHUB_SHA: ${{env.PR_SHA}}
```

- The main workflow:  https://github.com/alexfauquette/material-ui-x/blob/master/.github/workflows/vale-action.yml
- The workflow to get PR SHA: https://github.com/alexfauquette/material-ui-x/blob/master/.github/workflows/vale-pr-check.yml
- The configuration file: https://github.com/alexfauquette/material-ui-x/blob/master/.vale.ini
