### ISSUE TITLE
Feature Wish: configure .vale.ini location via "with"

### ISSUE THREAD

**Issue by nkuehn** [vale-cli/vale-action#9]
Hi, thanks for providing an "offical" github action that puts checks on the specific lines! 
I was short before building it myself and saved a lot of time. 

It would allow for a more consistent and reliable configuration if I were able to **override the default config file location from the repository root to another path in the repository.** 

I agree that convention over configuration is a good idea, so here's a better description of the use case to explain the need: 

**Background /Setup**

Our Documentation is spread across different repositories and we maintain a central vale configuration (both .ini file and a set of custom rules) as a public NPM package which is then a dependency in every repository that generates documentation.  

I can override the styles location merging a local  `.vale.ini` with a styles path override to a remotely pulled `.vale.ini`  but pulling one part (vale.ini) via HTTP from master and the other part (the style rules) via NPM in a specific version will lead to issues at some point (e.g. the ini referencing a rule that is not published yet). 

In practice, i would do a dependency install before the vale action step, pass `node_modules/@commercetools-docs/writing-style/.vale.ini` as the config path and that's it.

Other use cases for custom config paths are e.g. monorepositories with many packages that have local .vale.ini files in subfolders.

**Comment by BenRoe** [comment]
@jdkato Is there a recommended way to use consistent configuration files for vale with multiple projects?

**Comment by jdkato** [comment]
@BenRoe, you can have a look at https://github.com/errata-ai/vale/issues/386#issue-1071024321 for a recent proposal.

**Comment by jdkato** [comment]
This is now possible by using the new reviewdog-based action with `vale_flags`:

```yaml
name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          vale_flags: "--config=.github/.vale.ini"
          debug: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
